### ISSUE TITLE
really really really slow

### ISSUE THREAD

**Issue by shopmeister** [FriendsOfShopware/FroshBunnycdnMediaStorage#10]
i have the issue that it is really slow to transfer the media files to bunnycdn. its about 13 files in 15 minutes. thats crazy. i there something i can do?

**Comment by tinect** [comment]
Hey @epagogmbh 

You are transfering existing files with the command? This is a little bit slow, but normally not that much. I think BunnyCDN-API is currently slow, but I cannot test this at the moment.

Meanwhile, are you able to transfer the files by FTP?

**Comment by shopmeister** [comment]
oh yes, i could tranfer it manually by ftp. maybe thats faster. just add the whole media folder to bunny cdn? it would be interesting to increase speed to migrate files. it would take weeks to transfer with the slow speed i had ;) thanks for the fast answer.

**Comment by tinect** [comment]
Oh yeah. That's true! But normally it's a little bit faster.
I'll check if there could be an other and faster way these days. 
And yes: upload entire media folder.

**Comment by shopmeister** [comment]
i solved the problem, when i changed the api key to the right key. you can find it in the created storage under API Access -> Password. My issue was, that i tryed to use the account api key what not worked.

**Comment by tinect** [comment]
Okay, now it's acceptable `fast` for you? :-)

**Comment by shopmeister** [comment]
it is - thank you , great work ;)
