### ISSUE TITLE
Exception, message: "File not found: media/image/..."

### ISSUE THREAD

**Issue by hagmann** [FriendsOfShopware/FroshBunnycdnMediaStorage#11]
The plugin has been installed and the config.php is set according to the manual.
Uplodaing a file through the file explorer does not work and we receive this error message:

exception: {_class: "Exception"}
_class: "Exception"
message: "File not found: media/image/cimage_6_kat1_1.jpg"
success: false

This is the config.php cdn section

    'cdn' => [
        'backend' => 'bunnycdn',
        'liveMigration' => true,
        'adapters' => [
            'bunnycdn' =>
                [
                    'type' => 'bunnycdn',
                    'mediaUrl' => 'https://xxxxxxxx.b-cdn.net/',
                    'apiUrl' => 'https://storage.bunnycdn.com/xxxxxxxxxx/',
                    'apiKey' => 'xxxxxxxxxxxxxxxxxxxxxxxxx'
                ]
        ]
    ]

Afterwards, the file is still uploaded to bunnycdn and the link to medium shows the image.
But in the Shopware media manager, there is no preview visible for this image.

**Comment by tinect** [comment]
Hey @hagmann 
what do you mean with `file explorer`?
Which version of shopware are you using?

Could you please check without `liveMigration`? IIRC this is buggy.

**Comment by hagmann** [comment]
Hi @tinect 

With file explorer, I mean the media manager (Shopware Backend)
I already checked without liveMigration, same result.

Version 5.5.6

![image](https://user-images.githubusercontent.com/11349379/99543193-33361800-29b3-11eb-8a6d-934f3ac55279.png)

This might be misleading, as  the POST /backend/mediaManager/upload?albumID=-3 shows this error:
![image](https://user-images.githubusercontent.com/11349379/99543249-45b05180-29b3-11eb-92bb-914074a82ee2.png)

**Comment by tinect** [comment]
Okay, you are sure your upload has created the file into bunnycdn or has the file been there before you upload?

**Comment by tinect** [comment]
Closed due too inactivity.
