### ISSUE TITLE
Local copy

### ISSUE THREAD

**Issue by allesolive** [FriendsOfShopware/FroshBunnycdnMediaStorage#12]
we using the plugin since some days and it works good. 
However we using an Product Designer that creates and upload to the media folder files and want to read them as well there. This creates an error as the Product Designer looking for the local file that has been uploaded to the cdn by the plugin.

Is it possible to configure that an local copy is still on the server that the plugin can read them?

**Comment by tinect** [comment]
This option is no part of this plugin. You could create your own adapter managing this. But be aware: you'll have the files duplicated nonesense.

But, your product designer should respect shopware filesystems, not implementing it's own behaviour.
