### ISSUE TITLE
mediamanager emty after migration

### ISSUE THREAD

**Issue by shopmeister** [FriendsOfShopware/FroshBunnycdnMediaStorage#13]
hey! nice work - usd this three times now and all is working well.
for an actual project now the media manager is completly emty after migration.
CDN adapter in config.hp is correctly set. what could gone wrong?
sw:media:cleanup dont help. any ideas for that? shopware 5.6.9

**Comment by tinect** [comment]
Hey, thank you.
Is there any errored result in the devtools network tab?

**Comment by shopmeister** [comment]
hey! thanks for the ultrafast reply. i checked a lot, cause there were no entrys in console or network tab.

**Comment by shopmeister** [comment]
t was a "dreischild" plugin for image optimization what killed the media manager. after uninstall, everything worked well.
