### ISSUE TITLE
New images no thumbnails

### ISSUE THREAD

**Issue by Zineys** [FriendsOfShopware/FroshBunnycdnMediaStorage#15]
### Question

Hello, slowly I despair a little, unfortunately, which is why I hope for help here.

Under SW6 in other projects everything works like a charm but currently I'm working on a SW5 store. We have installed and configured the plugin as described (https://support.bunny.net/hc/en-us/articles/360018577551-How-to-speed-up-your-Shopware-site-with-BunnyCDN). 

The images are all in storage(BunnyCDN) and are outputting as desired. So far so good. Now when I upload images an error message appears from SW (The selected file exceeds the maximum allowed upload size. Please select another file). This error appeared only after I switched from adapter from local to bunnycdn. Funny thing is that the file is still uploaded and also transferred to storage but no thumbnails are created.

When I try to generate thumbnails via sw:thumbnail:generate
I get the following error:
Generating Thumbnails for Album Blog (ID: -11)
    0 [>---------------------------]
Generating Thumbnails for Album Einkaufswelten (ID: -3)
  0/63 [>---------------------------]   0%PHP Fatal error:  Uncaught TypeError: stream_get_contents(): Argument #1 ($stream) must be of type resource, bool given in /var/www/vhosts/web901.michelle.webhoster.ag/httpdocs/_frohmarie/custom/plugins/FroshBunnycdnMediaStorage/Components/BunnyCDNAdapter.php:302

And yes, before I changed
local to bunnyCDN, the media upload and thumbnails worked.

    'cdn' => [
        'backend' => 'local', /* change this after transfer to bunnycdn */
            'adapters' => [
            

Do you have any idea what this could be?

Best Regards

Timo

**Comment by tinect** [comment]
Hey, you are sure the credentials are correct?

Your error says the file hasn't been found.

**Comment by Zineys** [comment]
Hello, thank you for your quick reply.

Is it possible to migrate media files to the storage without correct credentials?
bin/console sw:media:migrate --from=local --to=bunnycdn

Because this part worked so far.

**Comment by tinect** [comment]
No, it needs access to the system to download it.

**Comment by Zineys** [comment]
So when I upload any image, first I get the error message about the file size and then the image is uploaded anyway. I see it in the SW5 backend in the media library and can find it under the path in the URL also at BunnyCDN in storage. Means so far it works but as I said no thumbnails are created as usual in Shopware..


![upload-error](https://user-images.githubusercontent.com/37153319/198629665-2965e988-db7b-4145-a2c4-2222595ad3eb.PNG)
![thumbnails](https://user-images.githubusercontent.com/37153319/198629676-c95031a8-4dbb-4001-a9a3-50415921f054.PNG)
![no-thumbnails](https://user-images.githubusercontent.com/37153319/198629683-a3a2b372-a212-4217-902c-84e74c7e2d0b.PNG)

**Comment by tinect** [comment]
Damn :-( really creepy.
Which version of shopware and BunnyCDN-plugin do you have installed?

We'll try to reproduce it in the next days.

**Comment by Zineys** [comment]
If I can help in any way then let me know.
Shopware Version 5.7.15
BunnyCDN Plugin: 1.0.4

I wish I even knew what exactly I am looking for. I have had a few var_dumps output in the plugin but everything seems to be running normally so far.... If it is the server, I would like to know why and what I can tell the hoster..
Our elaborate workaround is currently to switch the plugin to local, upload the images, migrate images to stroage and then switch back to bunnycdn in the config.

Here is some more info if necessary.
![image](https://user-images.githubusercontent.com/37153319/198700335-30358475-5108-403e-a6ba-31ad706b69ad.png)
![image](https://user-images.githubusercontent.com/37153319/198700393-555a5dac-2a8f-4b85-8911-ffe8448b2e05.png)

**Comment by tinect** [comment]
Sadly, I cannot reproduce the error.
To help you further with this issue, could you please send me access to a test environment where you have the issue?
I would need:
- shell access (ssh)
- backend access

You can reach me at slack.shopware.com.

**Comment by tinect** [comment]
Hey @Zineys 
thank you.

We got the problem: curl and/or ssl on the server is broken. Please contact the hoster. But better (as discussed), switch hoster ;-)
