### ISSUE TITLE
sw:thumbnail:generate fails with php 8

### ISSUE THREAD

**Issue by shopmeister** [FriendsOfShopware/FroshBunnycdnMediaStorage#19]
### PHP Version

8.2.3

### Shopware Version

5.7.17

### Actual behaviour

thumbnail:generation process is not working from backend or console, if changing php from 7.4 to 8.2.x
it is working if config.php contains a cdn > local - it is now, if it contains the bunnycdn as cdn
media manager is showing images correctly
just the image processing is not working for thumbnail genaueration., it fails with a fopen() issue.

### Expected behaviour

Full Stack Trace:

Fatal error: Uncaught TypeError: fclose(): supplied resource is not a valid stream resource in /var/www/clients/client1/web1/web/shop/engine/Shopware/Components/Thumbnail/Generator/Basic.php:333

Stack trace:

#0 /var/www/clients/client1/web1/web/shop/engine/Shopware/Components/Thumbnail/Generator/Basic.php(333): fclose()

#1 /var/www/clients/client1/web1/web/shop/engine/Shopware/Components/Thumbnail/Generator/Basic.php(295): Shopware\Components\Thumbnail\Generator\Basic->uploadImage()

#2 /var/www/clients/client1/web1/web/shop/engine/Shopware/Components/Thumbnail/Generator/Basic.php(106): Shopware\Components\Thumbnail\Generator\Basic->optimizeImage()

#3 /var/www/clients/client1/web1/web/shop/engine/Shopware/Components/Thumbnail/Manager.php(145): Shopware\Components\Thumbnail\Generator\Basic->createThumbnail()

#4 /var/www/clients/client1/web1/web/shop/engine/Shopware/Models/Media/Media.php(1187): Shopware\Components\Thumbnail\Manager->createMediaThumbnail()

#5 /var/www/clients/client1/web1/web/shop/engine/Shopware/Models/Media/Media.php(856): Shopware\Models\Media\Media->createThumbnail()

#6 /var/www/clients/client1/web1/web/shop/engine/Shopware/Models/Media/Media.php(706): Shopware\Models\Media\Media->loadThumbnails()

#7 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php(83): Shopware\Models\Media\Media->onLoad()

#8 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/HydrationCompleteHandler.php(66): Doctrine\ORM\Event\ListenersInvoker->invoke()

#9 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3654): Doctrine\ORM\Internal\HydrationCompleteHandler->hydrationComplete()

#10 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(52): Doctrine\ORM\UnitOfWork->hydrationComplete()

#11 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(272): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->cleanup()

#12 /var/www/clients/client1/web1/web/shop/engine/Library/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(803): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll()

#13 /var/www/clients/client1/web1/web/shop/engine/Library/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(867): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load()

#14 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2798): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadOneToOneEntity()

#15 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(266): Doctrine\ORM\UnitOfWork->createEntity()

#16 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(492): Doctrine\ORM\Internal\Hydration\ObjectHydrator->getEntity()

#17 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(148): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateRowData()

#18 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(270): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateAllData()

#19 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1234): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll()

#20 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1175): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache()

#21 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(911): Doctrine\ORM\AbstractQuery->execute()

#22 /var/www/clients/client1/web1/web/shop/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(171): Doctrine\ORM\AbstractQuery->getResult()

#23 /var/www/clients/client1/web1/web/shop/engine/Shopware/Commands/ThumbnailGenerateCommand.php(207): Doctrine\ORM\Tools\Pagination\Paginator->getIterator()

#24 /var/www/clients/client1/web1/web/shop/engine/Shopware/Commands/ThumbnailGenerateCommand.php(140): Shopware\Commands\ThumbnailGenerateCommand->createAlbumThumbnails()

#25 /var/www/clients/client1/web1/web/shop/vendor/symfony/console/Command/Command.php(255): Shopware\Commands\ThumbnailGenerateCommand->execute()

#26 /var/www/clients/client1/web1/web/shop/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()

#27 /var/www/clients/client1/web1/web/shop/engine/Shopware/Components/Console/Application.php(131): Symfony\Component\Console\Application->doRunCommand()

#28 /var/www/clients/client1/web1/web/shop/vendor/symfony/console/Application.php(273): Shopware\Components\Console\Application->doRunCommand()

#29 /var/www/clients/client1/web1/web/shop/engine/Shopware/Components/Console/Application.php(110): Symfony\Component\Console\Application->doRun()

#30 /var/www/clients/client1/web1/web/shop/vendor/symfony/console/Application.php(149): Shopware\Components\Console\Application->doRun()

#31 /var/www/clients/client1/web1/web/shop/bin/console(38): Symfony\Component\Console\Application->run()

#32 {main}

  thrown in /var/www/clients/client1/web1/web/shop/engine/Shopware/Components/Thumbnail/Generator/Basic.php on line 333

### Steps to Reproduce?

try sw:thumbnail:generate

**Comment by shyim** [comment]
It's a bug in Shopware 5 core that closes the stream. Maybe make a PR to check that the stream is still open to close it
