### ISSUE TITLE
Uninstallation

### ISSUE THREAD

**Issue by ace16vitamine** [FriendsOfShopware/FroshBunnycdnMediaStorage#20]
### Question

Hi there,

do I understand right that...

- the local files will be deleted after the migration?
- If I add new products, do I need to start the migration again (eg. via script)? 
- uninstallation is only: delete the plugin and change the config file back. Right?

Thanks
Stefan

**Comment by tinect** [comment]
Hi, thank you for asking :-) 

the topic is "Uninstallation", but your first questions are general questions, aren't they?

1. Correct. Regarding shopware docs: 

>> After executing this command, you won't have any media file left on your local file system. The migration itself might take some time, depending on the number of media files you have. If you cancel the migration or your server crashes, you can continue the migration by running the command again.

2. no, it is done automatically, that is the base feature of such a filesystem adapter.

3. and migrate back the media. please check shopware docs linked in the readme.

**Comment by ace16vitamine** [comment]
Hey!

Thank you for fast responding.

It's a general question. I ask before I install it on our system.

The think is: We are working with JTL WAWI, products are deployed with the JTL Connector. That means that images will also transferred with JTL...

**Comment by tinect** [comment]
if the JTL connector is correctly using the shopware filesystem services there is no problem :-) 

You might want to test it on a dedicated test system.

While these are no topics to this plugin, but for shopware generally, you could check shopware community slack for more help regarding external filesystems.
