### ISSUE TITLE
Can't migrate back from bcdb

### ISSUE THREAD

**Issue by ace16vitamine** [FriendsOfShopware/FroshBunnycdnMediaStorage#21]
### Question

Dear all,

after migrating a test of round 380 images I have tried to migrate back from CDN to the local Shopware installation: bin/console sw:media:migrate --from=bunnycdn --to=local

But after 84% I received the following message:
failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in /var/www/xxx.de/custom/plugins/FroshBunnycdnMediaStorage/Components/BunnyCDNAdapter.php on line 319

In Filesystem.php line 112:
  League\Flysystem\Filesystem::putStream expects argument #2 to be a valid resource.  
sw:media:migrate [--from [FROM]] [--to [TO]] [--skip-scan]

Any Ideas what to do?

Thanks
Stefan

**Comment by tinect** [comment]
Hi Stefan,

sounds like BunnyCDN is resulting with an error:
could you try running the command again?

if it occurs again, please check by debugging which file is causing the error and verify it on the bunny filesystem.

You could do it by adding a check for is_resource at a named file, if not just break by exit or die.

**Comment by ace16vitamine** [comment]
I can do this later. 

Q: Is it enough to copy the files manually into the local folder?

**Comment by tinect** [comment]
> Q: Is it enough to copy the files manually into the local folder?

yes

**Comment by tinect** [comment]
I‘ll close due to inactivity.
