### ISSUE TITLE
Plugin not compatible with Shopware 5.5.8

### ISSUE THREAD

**Issue by mediagraphik** [FriendsOfShopware/FroshBunnycdnMediaStorage#5]
The given options wich are required for the config.php are no longer valid.

**In OptionsResolver.php line 645:**
The options "apiKey", "apiUrl" do not exist. Defined options are: "dir", "file", "mediaUrl", "permissions", "root", "type", "url".

**Comment by tinect** [comment]
Please have a deeper look into the sample config. The position where the values have to be set, aren't default-config-related.

**Comment by mediagraphik** [comment]
I'm not sure if I'm blind but I dont see an issue there.
And it is not the first time I use your plugin since we have it in use on multiple of our shops.
The only difference is that they are all SW 5.5.5 to 5.5.7.

```
return array(
	'db' => [
	        'username' => '***',
		'password' => '**',
		'dbname' => '**',
		'host' => 'localhost',
		'port' => '3306'
	],
	'cdn' => [
               'backend' => 'bunnycdn',
               'adapters' => [
               'bunnycdn' => [
                    'type' => 'local',
                    'mediaUrl' => 'https://***.b-cdn.net/',
                    'apiUrl' => 'https://storage.bunnycdn.com/***/',
                    'apiKey' => '**'
                    ]
               ]
        ]
);
```

Edit: I'm blind... sorry for the waste of time

**Comment by tinect** [comment]
'type' => 'local',
should be bunnycdn, as it's the name of adapter.

No problem :-)
