### ISSUE TITLE
Plugin Issue Cant Upload

### ISSUE THREAD

**Issue by JSNS9** [FriendsOfShopware/FroshBunnycdnMediaStorage#6]
I cant upload any new media using the extension.

The Migration worked fine although a bit slow.

Shopware version is 5.5.9 with PHP 7.0. is there any ideas? The config is:

 'cdn' =>
            [
                'backend' => 'bunnycdn',
                'adapters' => [
                    'bunnycdn' =>
                        array (
                            'type' => 'bunnycdn',
                            'mediaUrl' => 'https://cdn.gamingnerds.co.uk',
                            'apiUrl' => 'https://storage.bunnycdn.com/My Storage Name/',
                            'apiKey' => 'My Api Key'
                        )
            ]
            ]

**Comment by JSNS9** [comment]
Managed to find out that it was temfile being disabled in the PHP config

**Comment by tinect** [comment]
Hi @JSNS9 
Thank you. Nice to know it works for you now :-)
Will check for another solution.
